=== cshoosh/android_jumblejump/assets/Level/level.dtd
<!ELEMENT ROOT (LEVEL+)>
<!ELEMENT LEVEL (DESIGN+)>
<!ELEMENT DESIGN (ENTITIES)>

<!ELEMENT ENTITIES (ENTITY+)>
<!ELEMENT ENTITY (X,Y,TYPE)>
<!ELEMENT X (#PCDATA)>
<!ELEMENT Y (#PCDATA)>
<!ELEMENT TYPE EMPTY>

<!ATTLIST DESIGN
	no CDATA #REQUIRED>

<!ATTLIST LEVEL 
	lno CDATA #REQUIRED
	repeat CDATA #REQUIRED>

<!-- Type AtrributeList -->
<!ATTLIST TYPE
	type (Platform|Enemy) #REQUIRED
	sub (
		NML|BRK|DBL|DCY|MOV|ELE|REM
		
		PWN|KNT|WZR|BSS) #IMPLIED
	
	doubleInt CDATA #IMPLIED	
	
	item CDATA #IMPLIED
	align (CENTER|RIGHT|LEFT) #IMPLIED>

=== cshoosh/android_jumblejump/assets/Level/level7.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE LEVEL SYSTEM "level.dtd">
<ROOT>
    <LEVEL lno="7" repeat="1">
      <DESIGN no="1">
          <ENTITIES>
  <ENTITY>
    <X>20</X>
    <Y>10</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4" movableDis="50" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>58</X>
    <Y>25</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="CENTER" />
  </ENTITY>
  <ENTITY>
    <X>10</X>
    <Y>40</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4" movableDis="50" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>35</X>
    <Y>60</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.7" movableDis="35" movableInt="20" />
  </ENTITY>
  <ENTITY>
    <X>20</X>
    <Y>100</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="35" movableInt="20" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>100</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.8" movableDis="30" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>118</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="CENTER" />
  </ENTITY>
  <ENTITY>
    <X>75</X>
    <Y>115</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>45</X>
    <Y>148</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="35" movableInt="20" />
  </ENTITY>
  <ENTITY>
    <X>50</X>
    <Y>160</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.5" movableDis="35" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>10</X>
    <Y>180</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.3" movableDis="30" movableInt="20" />
  </ENTITY>
  <ENTITY>
    <X>40</X>
    <Y>200</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.3" movableDis="30" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>180</Y>
    <TYPE type="Platform" sub="NML" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>200</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>58</X>
    <Y>216</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>20</X>
    <Y>245</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>250</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>0</X>
    <Y>260</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4" movableDis="35" movableInt="20" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>290</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="30" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>10</X>
    <Y>295</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.5" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>305</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>43</X>
    <Y>310</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="CENTER" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>318</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>25</X>
    <Y>330</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.5" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>10</X>
    <Y>370</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="40" movableInt="20" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>370</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="30" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>30</X>
    <Y>385</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.8" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>10</X>
    <Y>395</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.7" movableDis="50" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>50</X>
    <Y>350</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
</ENTITIES>
      </DESIGN>
      <DESIGN no="2">
          <ENTITIES>
  <ENTITY>
    <X>24</X>
    <Y>5</Y>
    <TYPE type="Platform" sub="NML" />
  </ENTITY>
  <ENTITY>
    <X>65</X>
    <Y>12</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>9</X>
    <Y>20</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.5" movableDis="45" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>55</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="30" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>35</X>
    <Y>70</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>55</X>
    <Y>78</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>8</X>
    <Y>85</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="RIGHT" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>95</Y>
    <TYPE type="Platform" sub="NML" />
  </ENTITY>
  <ENTITY>
    <X>80</X>
    <Y>105</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>170</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4" movableDis="45" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>24</X>
    <Y>197</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="CENTER" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>205</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>75</X>
    <Y>215</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>60</X>
    <Y>260</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>255</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="LEFT" />
  </ENTITY>
  <ENTITY>
    <X>40</X>
    <Y>276</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.5" movableDis="30" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>20</X>
    <Y>300</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="30" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>315</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4.3" movableDis="45" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>68</X>
    <Y>350</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>40</X>
    <Y>333</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.5" movableDis="35" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>14</X>
    <Y>375</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="45" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>385</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="CENTER" />
  </ENTITY>
  <ENTITY>
    <X>45</X>
    <Y>395</Y>
    <TYPE type="Platform" sub="NML" />
  </ENTITY>
  <ENTITY>
    <X>30</X>
    <Y>185</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4" movableDis="30" movableInt="30" />
  </ENTITY>
  <ENTITY>
    <X>55</X>
    <Y>155</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>45</X>
    <Y>250</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="40" movableInt="0" />
  </ENTITY>
</ENTITIES>
      </DESIGN>
      <DESIGN no="3">
          <ENTITIES>
  <ENTITY>
    <X>5</X>
    <Y>10</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>35</X>
    <Y>60</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>67</X>
    <Y>45</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.5" movableDis="30" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>75</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="3.8" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>68</X>
    <Y>95</Y>
    <TYPE type="Platform" sub="NML" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>105</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="RIGHT" />
  </ENTITY>
  <ENTITY>
    <X>50</X>
    <Y>108</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>68</X>
    <Y>120</Y>
    <TYPE type="Platform" sub="NML" />
  </ENTITY>
  <ENTITY>
    <X>25</X>
    <Y>135</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4" movableDis="50" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>8</X>
    <Y>190</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.8" movableDis="45" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>78</X>
    <Y>190</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.8" movableDis="45" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>50</X>
    <Y>195</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>8</X>
    <Y>205</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4" movableDis="50" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>75</X>
    <Y>209</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>8</X>
    <Y>230</Y>
    <TYPE type="Platform" sub="DCY" />
  </ENTITY>
  <ENTITY>
    <X>45</X>
    <Y>270</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.8" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>70</X>
    <Y>255</Y>
    <TYPE type="Platform" sub="MOV" movableVer="True" movableVel="3.8" movableDis="40" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>5</X>
    <Y>280</Y>
    <TYPE type="Platform" sub="MOV" movableVer="False" movableVel="4" movableDis="50" movableInt="0" />
  </ENTITY>
  <ENTITY>
    <X>15</X>
    <Y>265</Y>
    <TYPE type="Platform" sub="NML" item="COIN" align="LEFT" />
  </ENTITY>
  <ENTITY>
    <X>18</X>
    <Y>310</Y>
    <TYPE type="Platform" sub="BRK" />
  </ENTITY>
  <ENTITY>
    <X>10</X>
